name: GLideN64

on: [push, workflow_dispatch]

jobs:

  GLideN64_Builder:
    strategy:
      fail-fast: false
    name: Backtrace with GLideN64_Builder...
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: microsoft/setup-msbuild@v1
      - name: Backtrace, build, backup binaries
        run: |
          copy projects\msvc\GLideN64_Builder.cmd ..\
          cd ..
          curl -L -O https://github.com/gonetz/GLideN64/releases/download/qt_build/qt-5_7_1-x86-msvc2017-static.7z
          7z x qt-5_7_1-x86-msvc2017-static.7z
          set "QTDIR_x86=%CD%\qt-5_7_1-x86-msvc2017-static"
          md binaries
          set "BUILDROUTE=%CD%\binaries"
          cd GLideN64
          goto begin
          :build
          	git reset --hard %~1
          	start /WAIT "" "..\GLideN64_Builder.cmd" --x86 --nopak --rebuild --nopjwtl --nomcl --q
          	if errorlevel 1 echo Failed %~1>> "%BUILDROUTE%\errors.txt"
          	start /WAIT "" "..\GLideN64_Builder.cmd" --clean
          	goto:EOF
          :begin
          call :build "ed1648c4381a06868c4fb35d86d8a3f005420bbe"
          call :build "c48841cfebff118af634135bc0f6a6a02bf4e7d4"
          call :build "3df3df9964fece2e5bbab07cfd1311da97d70201"
          call :build "4c8a40c6d876cad1576b27b63725af491516b12c"
          call :build "4f58d66e960a575a35ef3d783cca25fd71f5bc25"
          call :build "46d170e5fbd7b9533be00405452f5ea22f0f04c8"
          call :build "c14ae30c6d09995ca57494b39bc22f54d816ae2d"
          call :build "4974f64a569b1a74ec451727ae16dacdf97d100b"
          echo.
          if exist "%BUILDROUTE%\errors.txt" type "%BUILDROUTE%\errors.txt"
          echo.
          md pkg
          xcopy /e "%BUILDROUTE%" pkg
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: GLideN64_Backtrace_2020
          path: pkg/*
